os: linux
language: android
jdk: oraclejdk8

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - yes | sdkmanager "platforms;android-27"
  - gem install fastlane
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - cd photoducer
  - ../flutter/bin/flutter doctor
  - ../flutter/bin/flutter packages get
  - cd ..

before_script:
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in travis-ci-apk-upload.json.enc -d -a -out travis-ci-apk-upload.json
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in photoducer/android/Photoducer_Distribution.keystore.enc -d -a -out photoducer/android/Photoducer_Distribution.keystore
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in research-storage-account.json.enc -d -a -out research-storage-account.json
  - echo storePassword=$KEYSTORE_PASSWORD >> photoducer/android/key.properties
  - echo keyPassword=$KEY_PASSWORD >> photoducer/android/key.properties
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud auth activate-service-account --key-file=research-storage-account.json

script:
  - cd photoducer
  - gsutil cp gs://research-model-bucket/*.t* assets
  - ../flutter/bin/flutter -v build apk --release
  - cd ..
  - fastlane submit_playalpha

after_success:
  - echo "success"

after_failure:
  - echo "failure"

env:
  global:
  - TERM=dumb
  - secure: RDi7LFT/rcYhwdw9NV1heDg70MtkQfV9SNpSwFNyWzKEm9BifuIR+6nhdXA2Tj2/H274UmodLHs5Mor92ucE3lB7Tzn/vdTPwXG3Y+TS/dGQyDv/gmQPdwlTl0gEi39NK1Rfxi17tLAoZOxD9xoyBWnxVU+toNu+nLW95uKceY4gFi9dLaKkjpEjkuU7MxCwlhEHFG1vijiBfnzplBR4lC92atKcuZgMeUTwyJX4NIsDLHhW6x5pXqd7AVz0kvF6Bg0VFGOHlioWPuCqaxDSZFKdR68MBXgjd8CFi61YZnYpKyGMvnr0BaA4P8ZlPVz3CJuM5kZoQyCT1gbj/E/WFdXbI847MAcAjRM5OOIx3wLSaecwfjeHRaaK62paOl0izvBTIq1oI7mtwEMXBNkdVv0u91KlJ21GquW96oR/0zIwbDshmZJiLcaKk/cL0Pq1ttIJO4em7L6VZaSHjuReBPkgQtHZGEYAl2M3ws/Wyij6PvPlG31WnJyjeS6kFb0iKAPseTXM0wJmMy8T907lUoiUL4/aLxK/kB8UWRDcSCZwv1ckT1fRm+FfkN1lHZyna+NhuIK1Grk3jGD0ynRgo62ncQCFK0gNCE4OfvxpDDtAvT0v5irVHQBd9VX6jxkypGL9FjI7JTCuDN4rIad8vcrgC69ZvBa6/y06ugqg1G4=
  - secure: aU9hbMlc58+7qoSIskpX+Ensi/4Nm4d2Ho5mqVVgYy0zgutoLXPnt6OST+5yqAiU/SG1UEJrsrCVBT9XFO7/4KFKzH3QeOGsqqRgLstfL+oMaHrA+RniFYy+ycjRswsujQpQ/Dkjrysv7OFXH7q7Uwq3jgLRaDQoPy1A6KgsjOsN5KzT3QZ8naZdq+eeK+NpBqoRdUwYxbAA2BWxgQkH+6lXLcCmfH4KebFADwBc/8Hws6iiQVNamzg7M15H6n9NgJmnx272zI8j2boIB3otviEn97MRMOcc8tWN5NnIzP2SFfrFpuZHIZmoQQQKaN0wKai/cscsL6n1aNjzYgtlfz32cs/PnzVyroCoplc1Of73pXY/v+3IevCgIjjjYnAyTF1Dp7KjGbKE+lT1Q6vbTFjyOZEQ9LPiDZqWZtQcj5iUOKXLXfeC7sPHlMQiAxbPHZ7mQIRl/bix2rI3t3zMx4si5/GtCKI9z7gLDizlwZ3abcqp5CujBz88kYYZNpXsqrus7caXJbKF4saa+PKEvLArgNr0gmnQJhhW3dnVE/XK/4Y1UrncI4i86Hr58P1vyiXTD4zHMYyF/LEatPmXXl+m6BjohuTqJ6/Mpz1PuJPUKI/FrZltukkbLZk2QrU6J4n3YIRNsktUe5/crFSUYuU9SpNoQGMAiAbz7Sqrgps=
  - secure: e0V4vTGDp4ak0dpE3ggXLNZgoGMouXJA73UopbCNvkJS68V0M0oQuwgpqDe2Dl/BGGeGF9R91B0I36gVfqZF/AG9vlcG1wH3sa2V/hBHaUxDY1EAhE8ULvuNxdDZz5TYFeKoFJJHjRGhzmwnQPEgVrBJHLWgBJFceiTv0155EvRQQUhCb6au1Ih19O0T31iRXaIGgnwzi9rkugDvJztnu88dk6g6s89MOweNfK4fbz+cYt3n2DnXWw+saeE5l418hvZ2by3pvA3jFOxps5IP7LsrbUesuSsY+TEOlKXIWry2hb9ohuIHtbgTmPHc0HTVRWMpBm8JU2ZQALy0Y7MlQLqw6YjnQ8HOmiNeyM+6wNAY7X60gYhODf0Cjx+unq7GMGjyJxA3niFy73PkLoNu/Dwwfb/3RcSTdzUxsXsyUJFAS+VSTKTlJ0TnyrgPRPIbFD8/r+ITa2GwR8yaDkKo1QebAuZVY+Hg4aoTaDRNbTkXwRymHN+8/w/e1CJt2TfoTgFuCaZtrHuz29wDUJg6ldty3nsbGq0XdVpMdcrjoQXv2f1FQYsFKRxvf9ZAzl2M3uN1xaZSQ/FUaP6LvjmEhYbluDue4vXOA3YC+pwUoRPCnaAA9uDWoQAXBQ9Yo4unnjQu5Wnk2hYuXUxHMrJxYXJvp2lpvXEBFd/0UIHEoyQ=

