language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27

licenses:
  - 'android-sdk-license-.+'

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - yes | sdkmanager "platforms;android-27"
  - gem install fastlane

before_script:
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in travis-ci-apk-upload.json.enc -d -a -out travis-ci-apk-upload.json
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in photoducer/android/Photoducer_Distribution.keystore.enc -d -a -out photoducer/android/Photoducer_Distribution.keystore

script:
  - fastlane submit_playalpha

after_success:
  - echo "success"

after_failure:
  - echo "failure"

env:
  global:
  - TERM=dumb
