desc "Build and submit to Google Play Alpha"
lane :submit_playalpha do

  upload_to_play_store(
    track: "alpha",
    apk: "photoducer/build/app/outputs/apk/release/app-release.apk",
    mapping: "photoducer/build/app/outputs/mapping/release/mapping.txt"
  )

end
